from __future__ import annotations

from dataclasses import asdict, dataclass
from datetime import datetime, timezone
from typing import Any, Mapping


@dataclass(frozen=True)
class BusinessRef:
    """Durable provider identity suitable for cross-provider handoff.

    The contract intentionally carries no provider content beyond the provider key and
    durable identifier. Query/timestamp are provenance generated by this client.
    """

    provider: str
    provider_id: str
    source_query: str | None = None
    observed_at: str | None = None

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


@dataclass(frozen=True)
class BusinessRecord:
    """Provider-neutral local-business record for transient processing/integration.

    Whether a record may be persisted or redistributed is controlled by the source
    provider's terms, not by this dataclass. See COMPLIANCE.md and provider metadata.
    """

    provider: str
    provider_id: str | None
    name: str | None = None
    formatted_address: str | None = None
    latitude: float | None = None
    longitude: float | None = None
    primary_type: str | None = None
    types: str | None = None
    business_status: str | None = None
    website: str | None = None
    phone: str | None = None
    rating: float | None = None
    review_count: int | None = None
    provider_url: str | None = None
    source_query: str | None = None

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


def utc_observed_at() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat()


def _provider_id_from_google(place: Mapping[str, Any]) -> str | None:
    place_id = place.get("id")
    if place_id:
        return str(place_id)
    resource_name = place.get("name")
    if isinstance(resource_name, str) and resource_name.startswith("places/"):
        return resource_name.removeprefix("places/") or None
    return None


def google_place_to_ref(
    place: Mapping[str, Any],
    *,
    source_query: str | None = None,
    observed_at: str | None = None,
) -> BusinessRef | None:
    place_id = _provider_id_from_google(place)
    if not place_id:
        return None
    return BusinessRef(
        provider="google",
        provider_id=place_id,
        source_query=source_query,
        observed_at=observed_at,
    )


def google_place_to_business_record(
    place: Mapping[str, Any],
    *,
    source_query: str | None = None,
) -> BusinessRecord:
    display_name = place.get("displayName")
    if isinstance(display_name, Mapping):
        name = display_name.get("text")
    else:
        name = None

    location = place.get("location")
    if not isinstance(location, Mapping):
        location = {}

    types = place.get("types")
    if isinstance(types, list):
        types_text = ",".join(str(item) for item in types)
    elif types is None:
        types_text = None
    else:
        types_text = str(types)

    return BusinessRecord(
        provider="google",
        provider_id=_provider_id_from_google(place),
        name=str(name) if name is not None else None,
        formatted_address=place.get("formattedAddress"),
        latitude=location.get("latitude"),
        longitude=location.get("longitude"),
        primary_type=place.get("primaryType"),
        types=types_text,
        business_status=place.get("businessStatus"),
        website=place.get("websiteUri"),
        phone=place.get("internationalPhoneNumber") or place.get("nationalPhoneNumber"),
        rating=place.get("rating"),
        review_count=place.get("userRatingCount"),
        provider_url=place.get("googleMapsUri"),
        source_query=source_query,
    )
